export enum GuideType {
    None = 0,
    FightReady,
    SetSeat,
    StartFight,
    CastSkill,
    CastSkillOver,
    Win,
    ShowHeroList,
    ShowHeroListOver,
    showHeroItem,
    SnythHero,
    SnythHeroOver,
    fettersOver,
    fiveEnterMenus,
    fiveSelectWave,
    fiveFight,
    fiveStartFive,
    fiveWin,
    fiveUpLevel,
    fiveUpLevelOver,
    sixEnterMenus,
    sixSelectWave,
    sixFight,
    sixStartFive,
    sixWin,
    sevenEnterMenus,
    sevenSelectWave,
    sevenFight,
    sevenStartFive,

}