import Fun from "../tool/Fun";
import Dictionary from "../tool/Dictionary";

export default class SpriteKey {
    private static _idDict: Dictionary<string, string>;
    static get idDict(): Dictionary<string, string> {
        if (!SpriteKey._idDict) {
            SpriteKey.init();
        }
        return SpriteKey._idDict;
    }


    private static _extDict: Dictionary<string, string>;
    static get extDict(): Dictionary<string, string> {
        if (!SpriteKey._extDict) {
            SpriteKey.init();
        }
        return SpriteKey._extDict;
    }

    public static getId(key: string): string {
        if (!SpriteKey.idDict.hasKey(key)) {
            console.error('SpriteKey 不存在 key=' + key);
            return '';
        }
        return SpriteKey.idDict.getValue(key);
    }

    public static getUrl(key: string): string {
        return `ui://${SpriteKey.SoundPackageId}${SpriteKey.getId(key)}`;
    }


    public static getPath(key: string): string {
        return Fun.getResPath(`${SpriteKey.SoundPackageName}_${SpriteKey.getId(key)}${SpriteKey.extDict.getValue(key)}`, 'fgui');
    }


    private static init() {
        let dict = SpriteKey._idDict = new Dictionary<string, string>();
        dict.add("icon_1001.png", "9v6l0");
        dict.add("icon_1002.png", "9v6l1");
        dict.add("icon_1003.png", "9v6l2");
        dict.add("icon_1005.png", "9v6l3");
        dict.add("icon_1006.png", "9v6l4");
        dict.add("icon_1007.png", "9v6l5");
        dict.add("icon_1012.png", "9v6l6");
        dict.add("icon_1019.png", "ngrs1d");
        dict.add("icon_1020.png", "ngrs1e");
        dict.add("icon_1021.png", "ngrs1f");
        dict.add("race1.png", "ngrs1a");
        dict.add("star1.png", "gc5l2d");
        dict.add("Gift.png", "bxj0b");
        dict.add("diamond.png", "j5ct16");
        dict.add("jadeite.png", "j5ct1d");
        dict.add("gold.png", "j5ct17");
        dict.add("hero_12.png", "jg2u2g");
        dict.add("hero_14.png", "jg2u2h");
        dict.add("hero_15.png", "jg2u2i");
        dict.add("hero_18.png", "jg2u2j");
        dict.add("hero_2.png", "jg2u2k");
        dict.add("hero_30.png", "jg2u2l");
        dict.add("hero_5.png", "jg2u2m");
        dict.add("hero_6.png", "jg2u2n");
        dict.add("hero_9.png", "jg2u2o");
        dict.add("hero_21.png", "jg2u2p");
        dict.add("hero_22.png", "jg2u2q");
        dict.add("hero_24.png", "jg2u2r");
        dict.add("hero_25.png", "jg2u2s");
        dict.add("hero_26.png", "jg2u2t");
        dict.add("hero_27.png", "jg2u2u");
        dict.add("hero_34.png", "jg2u2v");
        dict.add("hero_35.png", "jg2u2w");
        dict.add("hero_4.png", "jg2u2x");
        dict.add("career1.png", "ngrs19");
        dict.add("career2.png", "h5p92y");
        dict.add("career3.png", "h5p92z");
        dict.add("career4.png", "h5p930");
        dict.add("career5.png", "h5p931");
        dict.add("career6.png", "h5p932");
        dict.add("career7.png", "h5p933");
        dict.add("race2.png", "h5p934");
        dict.add("race3.png", "h5p935");
        dict.add("race4.png", "h5p936");
        dict.add("race5.png", "h5p937");
        dict.add("icon_1004.png", "11av538");
        dict.add("icon_1008.png", "11av539");
        dict.add("icon_1009.png", "11av53a");
        dict.add("icon_1010.png", "11av53b");
        dict.add("icon_1011.png", "11av53c");
        dict.add("icon_1013.png", "11av53d");
        dict.add("icon_1014.png", "11av53e");
        dict.add("icon_1015.png", "11av53f");
        dict.add("icon_1016.png", "11av53g");
        dict.add("icon_1017.png", "11av53h");
        dict.add("icon_1018.png", "11av53i");
        dict.add("hero_1.png", "qyum53j");
        dict.add("hero_3.png", "qyum53k");
        dict.add("quality1.png", "czuw53l");
        dict.add("quality2.png", "czuw53m");
        dict.add("quality3.png", "czuw53n");
        dict.add("quality4.png", "czuw53o");
        dict.add("quality5.png", "czuw53p");
        dict.add("icon_skill01.png", "czuw53q");
        dict.add("icon_skill02.png", "czuw53r");
        dict.add("icon_skill03.png", "czuw53s");
        dict.add("icon_skill04.png", "czuw53t");
        dict.add("icon_skill05.png", "czuw53u");
        dict.add("icon_skill06.png", "czuw53v");
        dict.add("icon_skill07.png", "czuw53w");
        dict.add("icon_skill08.png", "czuw53x");
        dict.add("bigGold.png", "qvb653y");
        dict.add("middleGold.png", "qvb653z");
        dict.add("smalGold.png", "qvb6540");
        dict.add("hero_10.png", "lljr541");
        dict.add("hero_11.png", "lljr542");
        dict.add("hero_13.png", "lljr543");
        dict.add("hero_16.png", "lljr544");
        dict.add("hero_17.png", "lljr545");
        dict.add("hero_19.png", "lljr546");
        dict.add("hero_20.png", "lljr547");
        dict.add("hero_23.png", "lljr548");
        dict.add("hero_28.png", "lljr549");
        dict.add("hero_29.png", "lljr54a");
        dict.add("hero_31.png", "lljr54b");
        dict.add("hero_32.png", "lljr54c");
        dict.add("hero_33.png", "lljr54d");
        dict.add("hero_7.png", "lljr54e");
        dict.add("hero_8.png", "lljr54f");
        dict.add("point1.png", "lljr54g");
        dict.add("point2.png", "lljr54h");
        dict.add("point3.png", "lljr54i");
        dict.add("point4.png", "lljr54j");
        dict.add("point5.png", "lljr54k");
        dict.add("point6.png", "lljr54l");
        dict.add("point7.png", "lljr54m");
        dict.add("fun4.png", "bcle54n");
        dict.add("fun5.png", "bcle54o");
        dict.add("fun6.png", "bcle54p");
        dict.add("fun7.png", "bcle54q");
        dict.add("fun8.png", "bcle54r");
        dict.add("fun9.png", "bcle54s");
        dict.add("fun10.png", "bcle54t");
        dict.add("enemy_1.png", "bcle54u");
        dict.add("enemy_10.png", "bcle54v");
        dict.add("enemy_11.png", "bcle54w");
        dict.add("enemy_12.png", "bcle54x");
        dict.add("enemy_13.png", "bcle54y");
        dict.add("enemy_14.png", "bcle54z");
        dict.add("enemy_15.png", "bcle550");
        dict.add("enemy_16.png", "bcle551");
        dict.add("enemy_17.png", "bcle552");
        dict.add("enemy_18.png", "bcle553");
        dict.add("enemy_19.png", "bcle554");
        dict.add("enemy_2.png", "bcle555");
        dict.add("enemy_20.png", "bcle556");
        dict.add("enemy_21.png", "bcle557");
        dict.add("enemy_22.png", "bcle558");
        dict.add("enemy_23.png", "bcle559");
        dict.add("enemy_26.png", "bcle55a");
        dict.add("enemy_29.png", "bcle55b");
        dict.add("enemy_3.png", "bcle55c");
        dict.add("enemy_30.png", "bcle55d");
        dict.add("enemy_31.png", "bcle55e");
        dict.add("enemy_32.png", "bcle55f");
        dict.add("enemy_33.png", "bcle55g");
        dict.add("enemy_34.png", "bcle55h");
        dict.add("enemy_35.png", "bcle55i");
        dict.add("enemy_36.png", "bcle55j");
        dict.add("enemy_37.png", "bcle55k");
        dict.add("enemy_38.png", "bcle55l");
        dict.add("enemy_39.png", "bcle55m");
        dict.add("enemy_4.png", "bcle55n");
        dict.add("enemy_40.png", "bcle55o");
        dict.add("enemy_41.png", "bcle55p");
        dict.add("enemy_42.png", "bcle55q");
        dict.add("enemy_43.png", "bcle55r");
        dict.add("enemy_5.png", "bcle55s");
        dict.add("enemy_6.png", "bcle55t");
        dict.add("enemy_7.png", "bcle55u");
        dict.add("enemy_8.png", "bcle55v");
        dict.add("enemy_9.png", "bcle55w");
        dict.add("hero_name_1.png", "ajdp55x");
        dict.add("hero_name_10.png", "ajdp55y");
        dict.add("hero_name_11.png", "ajdp55z");
        dict.add("hero_name_12.png", "ajdp560");
        dict.add("hero_name_13.png", "ajdp561");
        dict.add("hero_name_14.png", "ajdp562");
        dict.add("hero_name_15.png", "ajdp563");
        dict.add("hero_name_16.png", "ajdp564");
        dict.add("hero_name_17.png", "ajdp565");
        dict.add("hero_name_18.png", "ajdp566");
        dict.add("hero_name_19.png", "ajdp567");
        dict.add("hero_name_2.png", "ajdp568");
        dict.add("hero_name_20.png", "ajdp569");
        dict.add("hero_name_21.png", "ajdp56a");
        dict.add("hero_name_22.png", "ajdp56b");
        dict.add("hero_name_23.png", "ajdp56c");
        dict.add("hero_name_24.png", "ajdp56d");
        dict.add("hero_name_25.png", "ajdp56e");
        dict.add("hero_name_26.png", "ajdp56f");
        dict.add("hero_name_27.png", "ajdp56g");
        dict.add("hero_name_28.png", "ajdp56h");
        dict.add("hero_name_29.png", "ajdp56i");
        dict.add("hero_name_3.png", "ajdp56j");
        dict.add("hero_name_30.png", "ajdp56k");
        dict.add("hero_name_31.png", "ajdp56l");
        dict.add("hero_name_32.png", "ajdp56m");
        dict.add("hero_name_33.png", "ajdp56n");
        dict.add("hero_name_34.png", "ajdp56o");
        dict.add("hero_name_35.png", "ajdp56p");
        dict.add("hero_name_4.png", "ajdp56q");
        dict.add("hero_name_5.png", "ajdp56r");
        dict.add("hero_name_6.png", "ajdp56s");
        dict.add("hero_name_7.png", "ajdp56t");
        dict.add("hero_name_8.png", "ajdp56u");
        dict.add("hero_name_9.png", "ajdp56v");
        dict.add("enemy_24.png", "94yv56w");
        dict.add("enemy_25.png", "94yv56x");
        dict.add("enemy_27.png", "94yv56y");
        dict.add("enemy_28.png", "94yv56z");
        dict.add("fun3.png", "94yv2r");
        dict.add("QualityName_0.png", "eaol570");
        dict.add("QualityName_1.png", "eaol571");
        dict.add("QualityName_2.png", "eaol572");
        dict.add("QualityName_3.png", "eaol573");
        dict.add("QualityName_4.png", "eaol574");
        dict.add("wxTop.png", "94yv7");
        dict.add("fun11.png", "eaol2y");

        let exts = SpriteKey._extDict = new Dictionary<string, string>();
        exts.add("icon_1001.png", ".png");
        exts.add("icon_1002.png", ".png");
        exts.add("icon_1003.png", ".png");
        exts.add("icon_1005.png", ".png");
        exts.add("icon_1006.png", ".png");
        exts.add("icon_1007.png", ".png");
        exts.add("icon_1012.png", ".png");
        exts.add("icon_1019.png", ".png");
        exts.add("icon_1020.png", ".png");
        exts.add("icon_1021.png", ".png");
        exts.add("race1.png", ".png");
        exts.add("star1.png", ".png");
        exts.add("Gift.png", ".png");
        exts.add("diamond.png", ".png");
        exts.add("jadeite.png", ".png");
        exts.add("gold.png", ".png");
        exts.add("hero_12.png", ".png");
        exts.add("hero_14.png", ".png");
        exts.add("hero_15.png", ".png");
        exts.add("hero_18.png", ".png");
        exts.add("hero_2.png", ".png");
        exts.add("hero_30.png", ".png");
        exts.add("hero_5.png", ".png");
        exts.add("hero_6.png", ".png");
        exts.add("hero_9.png", ".png");
        exts.add("hero_21.png", ".png");
        exts.add("hero_22.png", ".png");
        exts.add("hero_24.png", ".png");
        exts.add("hero_25.png", ".png");
        exts.add("hero_26.png", ".png");
        exts.add("hero_27.png", ".png");
        exts.add("hero_34.png", ".png");
        exts.add("hero_35.png", ".png");
        exts.add("hero_4.png", ".png");
        exts.add("career1.png", ".png");
        exts.add("career2.png", ".png");
        exts.add("career3.png", ".png");
        exts.add("career4.png", ".png");
        exts.add("career5.png", ".png");
        exts.add("career6.png", ".png");
        exts.add("career7.png", ".png");
        exts.add("race2.png", ".png");
        exts.add("race3.png", ".png");
        exts.add("race4.png", ".png");
        exts.add("race5.png", ".png");
        exts.add("icon_1004.png", ".png");
        exts.add("icon_1008.png", ".png");
        exts.add("icon_1009.png", ".png");
        exts.add("icon_1010.png", ".png");
        exts.add("icon_1011.png", ".png");
        exts.add("icon_1013.png", ".png");
        exts.add("icon_1014.png", ".png");
        exts.add("icon_1015.png", ".png");
        exts.add("icon_1016.png", ".png");
        exts.add("icon_1017.png", ".png");
        exts.add("icon_1018.png", ".png");
        exts.add("hero_1.png", ".png");
        exts.add("hero_3.png", ".png");
        exts.add("quality1.png", ".png");
        exts.add("quality2.png", ".png");
        exts.add("quality3.png", ".png");
        exts.add("quality4.png", ".png");
        exts.add("quality5.png", ".png");
        exts.add("icon_skill01.png", ".png");
        exts.add("icon_skill02.png", ".png");
        exts.add("icon_skill03.png", ".png");
        exts.add("icon_skill04.png", ".png");
        exts.add("icon_skill05.png", ".png");
        exts.add("icon_skill06.png", ".png");
        exts.add("icon_skill07.png", ".png");
        exts.add("icon_skill08.png", ".png");
        exts.add("bigGold.png", ".png");
        exts.add("middleGold.png", ".png");
        exts.add("smalGold.png", ".png");
        exts.add("hero_10.png", ".png");
        exts.add("hero_11.png", ".png");
        exts.add("hero_13.png", ".png");
        exts.add("hero_16.png", ".png");
        exts.add("hero_17.png", ".png");
        exts.add("hero_19.png", ".png");
        exts.add("hero_20.png", ".png");
        exts.add("hero_23.png", ".png");
        exts.add("hero_28.png", ".png");
        exts.add("hero_29.png", ".png");
        exts.add("hero_31.png", ".png");
        exts.add("hero_32.png", ".png");
        exts.add("hero_33.png", ".png");
        exts.add("hero_7.png", ".png");
        exts.add("hero_8.png", ".png");
        exts.add("point1.png", ".png");
        exts.add("point2.png", ".png");
        exts.add("point3.png", ".png");
        exts.add("point4.png", ".png");
        exts.add("point5.png", ".png");
        exts.add("point6.png", ".png");
        exts.add("point7.png", ".png");
        exts.add("fun4.png", ".png");
        exts.add("fun5.png", ".png");
        exts.add("fun6.png", ".png");
        exts.add("fun7.png", ".png");
        exts.add("fun8.png", ".png");
        exts.add("fun9.png", ".png");
        exts.add("fun10.png", ".png");
        exts.add("enemy_1.png", ".png");
        exts.add("enemy_10.png", ".png");
        exts.add("enemy_11.png", ".png");
        exts.add("enemy_12.png", ".png");
        exts.add("enemy_13.png", ".png");
        exts.add("enemy_14.png", ".png");
        exts.add("enemy_15.png", ".png");
        exts.add("enemy_16.png", ".png");
        exts.add("enemy_17.png", ".png");
        exts.add("enemy_18.png", ".png");
        exts.add("enemy_19.png", ".png");
        exts.add("enemy_2.png", ".png");
        exts.add("enemy_20.png", ".png");
        exts.add("enemy_21.png", ".png");
        exts.add("enemy_22.png", ".png");
        exts.add("enemy_23.png", ".png");
        exts.add("enemy_26.png", ".png");
        exts.add("enemy_29.png", ".png");
        exts.add("enemy_3.png", ".png");
        exts.add("enemy_30.png", ".png");
        exts.add("enemy_31.png", ".png");
        exts.add("enemy_32.png", ".png");
        exts.add("enemy_33.png", ".png");
        exts.add("enemy_34.png", ".png");
        exts.add("enemy_35.png", ".png");
        exts.add("enemy_36.png", ".png");
        exts.add("enemy_37.png", ".png");
        exts.add("enemy_38.png", ".png");
        exts.add("enemy_39.png", ".png");
        exts.add("enemy_4.png", ".png");
        exts.add("enemy_40.png", ".png");
        exts.add("enemy_41.png", ".png");
        exts.add("enemy_42.png", ".png");
        exts.add("enemy_43.png", ".png");
        exts.add("enemy_5.png", ".png");
        exts.add("enemy_6.png", ".png");
        exts.add("enemy_7.png", ".png");
        exts.add("enemy_8.png", ".png");
        exts.add("enemy_9.png", ".png");
        exts.add("hero_name_1.png", ".png");
        exts.add("hero_name_10.png", ".png");
        exts.add("hero_name_11.png", ".png");
        exts.add("hero_name_12.png", ".png");
        exts.add("hero_name_13.png", ".png");
        exts.add("hero_name_14.png", ".png");
        exts.add("hero_name_15.png", ".png");
        exts.add("hero_name_16.png", ".png");
        exts.add("hero_name_17.png", ".png");
        exts.add("hero_name_18.png", ".png");
        exts.add("hero_name_19.png", ".png");
        exts.add("hero_name_2.png", ".png");
        exts.add("hero_name_20.png", ".png");
        exts.add("hero_name_21.png", ".png");
        exts.add("hero_name_22.png", ".png");
        exts.add("hero_name_23.png", ".png");
        exts.add("hero_name_24.png", ".png");
        exts.add("hero_name_25.png", ".png");
        exts.add("hero_name_26.png", ".png");
        exts.add("hero_name_27.png", ".png");
        exts.add("hero_name_28.png", ".png");
        exts.add("hero_name_29.png", ".png");
        exts.add("hero_name_3.png", ".png");
        exts.add("hero_name_30.png", ".png");
        exts.add("hero_name_31.png", ".png");
        exts.add("hero_name_32.png", ".png");
        exts.add("hero_name_33.png", ".png");
        exts.add("hero_name_34.png", ".png");
        exts.add("hero_name_35.png", ".png");
        exts.add("hero_name_4.png", ".png");
        exts.add("hero_name_5.png", ".png");
        exts.add("hero_name_6.png", ".png");
        exts.add("hero_name_7.png", ".png");
        exts.add("hero_name_8.png", ".png");
        exts.add("hero_name_9.png", ".png");
        exts.add("enemy_24.png", ".png");
        exts.add("enemy_25.png", ".png");
        exts.add("enemy_27.png", ".png");
        exts.add("enemy_28.png", ".png");
        exts.add("fun3.png", ".png");
        exts.add("QualityName_0.png", ".png");
        exts.add("QualityName_1.png", ".png");
        exts.add("QualityName_2.png", ".png");
        exts.add("QualityName_3.png", ".png");
        exts.add("QualityName_4.png", ".png");
        exts.add("wxTop.png", ".png");
        exts.add("fun11.png", ".png");

    }

	static SoundPackageName = "FSprite";
	static SoundPackageId = "88du1wab";

	public static icon_1001 = "icon_1001.png";
	public static icon_1002 = "icon_1002.png";
	public static icon_1003 = "icon_1003.png";
	public static icon_1005 = "icon_1005.png";
	public static icon_1006 = "icon_1006.png";
	public static icon_1007 = "icon_1007.png";
	public static icon_1012 = "icon_1012.png";
	public static icon_1019 = "icon_1019.png";
	public static icon_1020 = "icon_1020.png";
	public static icon_1021 = "icon_1021.png";
	public static race1 = "race1.png";
	public static star1 = "star1.png";
	public static Gift = "Gift.png";
	public static diamond = "diamond.png";
	public static jadeite = "jadeite.png";
	public static gold = "gold.png";
	public static hero_12 = "hero_12.png";
	public static hero_14 = "hero_14.png";
	public static hero_15 = "hero_15.png";
	public static hero_18 = "hero_18.png";
	public static hero_2 = "hero_2.png";
	public static hero_30 = "hero_30.png";
	public static hero_5 = "hero_5.png";
	public static hero_6 = "hero_6.png";
	public static hero_9 = "hero_9.png";
	public static hero_21 = "hero_21.png";
	public static hero_22 = "hero_22.png";
	public static hero_24 = "hero_24.png";
	public static hero_25 = "hero_25.png";
	public static hero_26 = "hero_26.png";
	public static hero_27 = "hero_27.png";
	public static hero_34 = "hero_34.png";
	public static hero_35 = "hero_35.png";
	public static hero_4 = "hero_4.png";
	public static career1 = "career1.png";
	public static career2 = "career2.png";
	public static career3 = "career3.png";
	public static career4 = "career4.png";
	public static career5 = "career5.png";
	public static career6 = "career6.png";
	public static career7 = "career7.png";
	public static race2 = "race2.png";
	public static race3 = "race3.png";
	public static race4 = "race4.png";
	public static race5 = "race5.png";
	public static icon_1004 = "icon_1004.png";
	public static icon_1008 = "icon_1008.png";
	public static icon_1009 = "icon_1009.png";
	public static icon_1010 = "icon_1010.png";
	public static icon_1011 = "icon_1011.png";
	public static icon_1013 = "icon_1013.png";
	public static icon_1014 = "icon_1014.png";
	public static icon_1015 = "icon_1015.png";
	public static icon_1016 = "icon_1016.png";
	public static icon_1017 = "icon_1017.png";
	public static icon_1018 = "icon_1018.png";
	public static hero_1 = "hero_1.png";
	public static hero_3 = "hero_3.png";
	public static quality1 = "quality1.png";
	public static quality2 = "quality2.png";
	public static quality3 = "quality3.png";
	public static quality4 = "quality4.png";
	public static quality5 = "quality5.png";
	public static icon_skill01 = "icon_skill01.png";
	public static icon_skill02 = "icon_skill02.png";
	public static icon_skill03 = "icon_skill03.png";
	public static icon_skill04 = "icon_skill04.png";
	public static icon_skill05 = "icon_skill05.png";
	public static icon_skill06 = "icon_skill06.png";
	public static icon_skill07 = "icon_skill07.png";
	public static icon_skill08 = "icon_skill08.png";
	public static bigGold = "bigGold.png";
	public static middleGold = "middleGold.png";
	public static smalGold = "smalGold.png";
	public static hero_10 = "hero_10.png";
	public static hero_11 = "hero_11.png";
	public static hero_13 = "hero_13.png";
	public static hero_16 = "hero_16.png";
	public static hero_17 = "hero_17.png";
	public static hero_19 = "hero_19.png";
	public static hero_20 = "hero_20.png";
	public static hero_23 = "hero_23.png";
	public static hero_28 = "hero_28.png";
	public static hero_29 = "hero_29.png";
	public static hero_31 = "hero_31.png";
	public static hero_32 = "hero_32.png";
	public static hero_33 = "hero_33.png";
	public static hero_7 = "hero_7.png";
	public static hero_8 = "hero_8.png";
	public static point1 = "point1.png";
	public static point2 = "point2.png";
	public static point3 = "point3.png";
	public static point4 = "point4.png";
	public static point5 = "point5.png";
	public static point6 = "point6.png";
	public static point7 = "point7.png";
	public static fun4 = "fun4.png";
	public static fun5 = "fun5.png";
	public static fun6 = "fun6.png";
	public static fun7 = "fun7.png";
	public static fun8 = "fun8.png";
	public static fun9 = "fun9.png";
	public static fun10 = "fun10.png";
	public static enemy_1 = "enemy_1.png";
	public static enemy_10 = "enemy_10.png";
	public static enemy_11 = "enemy_11.png";
	public static enemy_12 = "enemy_12.png";
	public static enemy_13 = "enemy_13.png";
	public static enemy_14 = "enemy_14.png";
	public static enemy_15 = "enemy_15.png";
	public static enemy_16 = "enemy_16.png";
	public static enemy_17 = "enemy_17.png";
	public static enemy_18 = "enemy_18.png";
	public static enemy_19 = "enemy_19.png";
	public static enemy_2 = "enemy_2.png";
	public static enemy_20 = "enemy_20.png";
	public static enemy_21 = "enemy_21.png";
	public static enemy_22 = "enemy_22.png";
	public static enemy_23 = "enemy_23.png";
	public static enemy_26 = "enemy_26.png";
	public static enemy_29 = "enemy_29.png";
	public static enemy_3 = "enemy_3.png";
	public static enemy_30 = "enemy_30.png";
	public static enemy_31 = "enemy_31.png";
	public static enemy_32 = "enemy_32.png";
	public static enemy_33 = "enemy_33.png";
	public static enemy_34 = "enemy_34.png";
	public static enemy_35 = "enemy_35.png";
	public static enemy_36 = "enemy_36.png";
	public static enemy_37 = "enemy_37.png";
	public static enemy_38 = "enemy_38.png";
	public static enemy_39 = "enemy_39.png";
	public static enemy_4 = "enemy_4.png";
	public static enemy_40 = "enemy_40.png";
	public static enemy_41 = "enemy_41.png";
	public static enemy_42 = "enemy_42.png";
	public static enemy_43 = "enemy_43.png";
	public static enemy_5 = "enemy_5.png";
	public static enemy_6 = "enemy_6.png";
	public static enemy_7 = "enemy_7.png";
	public static enemy_8 = "enemy_8.png";
	public static enemy_9 = "enemy_9.png";
	public static hero_name_1 = "hero_name_1.png";
	public static hero_name_10 = "hero_name_10.png";
	public static hero_name_11 = "hero_name_11.png";
	public static hero_name_12 = "hero_name_12.png";
	public static hero_name_13 = "hero_name_13.png";
	public static hero_name_14 = "hero_name_14.png";
	public static hero_name_15 = "hero_name_15.png";
	public static hero_name_16 = "hero_name_16.png";
	public static hero_name_17 = "hero_name_17.png";
	public static hero_name_18 = "hero_name_18.png";
	public static hero_name_19 = "hero_name_19.png";
	public static hero_name_2 = "hero_name_2.png";
	public static hero_name_20 = "hero_name_20.png";
	public static hero_name_21 = "hero_name_21.png";
	public static hero_name_22 = "hero_name_22.png";
	public static hero_name_23 = "hero_name_23.png";
	public static hero_name_24 = "hero_name_24.png";
	public static hero_name_25 = "hero_name_25.png";
	public static hero_name_26 = "hero_name_26.png";
	public static hero_name_27 = "hero_name_27.png";
	public static hero_name_28 = "hero_name_28.png";
	public static hero_name_29 = "hero_name_29.png";
	public static hero_name_3 = "hero_name_3.png";
	public static hero_name_30 = "hero_name_30.png";
	public static hero_name_31 = "hero_name_31.png";
	public static hero_name_32 = "hero_name_32.png";
	public static hero_name_33 = "hero_name_33.png";
	public static hero_name_34 = "hero_name_34.png";
	public static hero_name_35 = "hero_name_35.png";
	public static hero_name_4 = "hero_name_4.png";
	public static hero_name_5 = "hero_name_5.png";
	public static hero_name_6 = "hero_name_6.png";
	public static hero_name_7 = "hero_name_7.png";
	public static hero_name_8 = "hero_name_8.png";
	public static hero_name_9 = "hero_name_9.png";
	public static enemy_24 = "enemy_24.png";
	public static enemy_25 = "enemy_25.png";
	public static enemy_27 = "enemy_27.png";
	public static enemy_28 = "enemy_28.png";
	public static fun3 = "fun3.png";
	public static QualityName_0 = "QualityName_0.png";
	public static QualityName_1 = "QualityName_1.png";
	public static QualityName_2 = "QualityName_2.png";
	public static QualityName_3 = "QualityName_3.png";
	public static QualityName_4 = "QualityName_4.png";
	public static wxTop = "wxTop.png";
	public static fun11 = "fun11.png";

    
}
