import Dictionary from "../Tool/Dictionary"; 

export default class HeroInfo {

    private static infDic: Dictionary<string, Dictionary<string, any>> = new Dictionary<string, Dictionary<string, any>>();
    private curInf: Dictionary<string, any> = new Dictionary<string, any>();

    public static serverInit(infDic: Dictionary<string, Dictionary<string, any>>): void {
        this.infDic.clear();
        this.infDic = infDic;
    }

    public get id(): any {
        return this.curInf.getValue("id");
    }
    public get name(): any {
        return this.curInf.getValue("name");
    }
    public get story(): any {
        return this.curInf.getValue("story");
    }
    public get quality(): any {
        return this.curInf.getValue("quality");
    }
    public get race(): any {
        return this.curInf.getValue("race");
    }
    public get career(): any {
        return this.curInf.getValue("career");
    }
    public get special_fetters(): any {
        return this.curInf.getValue("special_fetters");
    }
    public get range(): any {
        return this.curInf.getValue("range");
    }
    public get common_skill_id(): any {
        return this.curInf.getValue("common_skill_id");
    }
    public get common_cd(): any {
        return this.curInf.getValue("common_cd");
    }
    public get attack(): any {
        return this.curInf.getValue("attack");
    }
    public get crit(): any {
        return this.curInf.getValue("crit");
    }
    public get burst(): any {
        return this.curInf.getValue("burst");
    }
    public get special_skill_id(): any {
        return this.curInf.getValue("special_skill_id");
    }
    public get special_cd(): any {
        return this.curInf.getValue("special_cd");
    }
    public get special_atk(): any {
        return this.curInf.getValue("special_atk");
    }
    public get crit2(): any {
        return this.curInf.getValue("crit2");
    }
    public get burst2(): any {
        return this.curInf.getValue("burst2");
    }
    public get gain_method(): any {
        return this.curInf.getValue("gain_method");
    }
    constructor(id: string) {
        this.curInf = HeroInfo.infDic.getValue(id);
    }

    /**
     * 依据id获得配置信息
     * @param id 配置id
     */
    public static getInfo(id: any): HeroInfo {
        let ids: string = String(id);
        if (this.infDic.hasKey(ids)) {
            return new HeroInfo(ids);
        }
        return null;
    }
    private static infList: HeroInfo[] = null;
    public static getList(): Array<HeroInfo> {
        if (this.infList == null) {
            let list: string[] = this.infDic.getKeys();
            this.infList = [];
            for (let i = 0, len = list.length; i < len; i++) { 
                this.infList.push(new HeroInfo(list[i]));
            }
        }
        return this.infList;
    }
    static init() {
        this.infDic = new Dictionary<string, Dictionary<string, any>>();
        let dic1 = new Dictionary<string, any>();
        dic1.add("id", "1");
        dic1.add("name", "精灵小丽");
        dic1.add("story", "惊艳的姿色让人看过一眼就无法忘记，丑女榜蝉联十届冠军。");
        dic1.add("quality", "0");
        dic1.add("race", "1");
        dic1.add("career", "101");
        dic1.add("special_fetters", "0");
        dic1.add("range", "1");
        dic1.add("common_skill_id", "1");
        dic1.add("common_cd", "4");
        dic1.add("attack", "139.2");
        dic1.add("crit", "0.0232");
        dic1.add("burst", "1");
        dic1.add("special_skill_id", "1001");
        dic1.add("special_cd", "4");
        dic1.add("special_atk", "139.2");
        dic1.add("crit2", "0.0232");
        dic1.add("burst2", "1");
        dic1.add("gain_method", "0");
        this.infDic.add("1", dic1);
        let dic2 = new Dictionary<string, any>();
        dic2.add("id", "2");
        dic2.add("name", "神箭手");
        dic2.add("story", "丛林中的潜伏者，被射上一箭足以致命。");
        dic2.add("quality", "0");
        dic2.add("race", "2");
        dic2.add("career", "102");
        dic2.add("special_fetters", "0");
        dic2.add("range", "1");
        dic2.add("common_skill_id", "2");
        dic2.add("common_cd", "4");
        dic2.add("attack", "139.8");
        dic2.add("crit", "0.0231");
        dic2.add("burst", "2");
        dic2.add("special_skill_id", "1002");
        dic2.add("special_cd", "4");
        dic2.add("special_atk", "139.8");
        dic2.add("crit2", "0.0231");
        dic2.add("burst2", "2");
        dic2.add("gain_method", "0");
        this.infDic.add("2", dic2);
        let dic3 = new Dictionary<string, any>();
        dic3.add("id", "3");
        dic3.add("name", "顽皮舒克");
        dic3.add("story", "吃素？不存在的。");
        dic3.add("quality", "0");
        dic3.add("race", "3");
        dic3.add("career", "103");
        dic3.add("special_fetters", "0");
        dic3.add("range", "1");
        dic3.add("common_skill_id", "3");
        dic3.add("common_cd", "4");
        dic3.add("attack", "139.6");
        dic3.add("crit", "0.0233");
        dic3.add("burst", "1");
        dic3.add("special_skill_id", "1003");
        dic3.add("special_cd", "4");
        dic3.add("special_atk", "139.6");
        dic3.add("crit2", "0.0233");
        dic3.add("burst2", "1");
        dic3.add("gain_method", "0");
        this.infDic.add("3", dic3);
        let dic4 = new Dictionary<string, any>();
        dic4.add("id", "4");
        dic4.add("name", "百变小樱");
        dic4.add("story", "夜之精灵，熬夜对他来说绝对不是事儿！");
        dic4.add("quality", "0");
        dic4.add("race", "4");
        dic4.add("career", "104");
        dic4.add("special_fetters", "0");
        dic4.add("range", "1");
        dic4.add("common_skill_id", "4");
        dic4.add("common_cd", "4");
        dic4.add("attack", "140");
        dic4.add("crit", "0.0235");
        dic4.add("burst", "2");
        dic4.add("special_skill_id", "1004");
        dic4.add("special_cd", "4");
        dic4.add("special_atk", "140");
        dic4.add("crit2", "0.0235");
        dic4.add("burst2", "2");
        dic4.add("gain_method", "0");
        this.infDic.add("4", dic4);
        let dic5 = new Dictionary<string, any>();
        dic5.add("id", "5");
        dic5.add("name", "拳王泰森");
        dic5.add("story", "为了练肌肉，天天泡健身房的上进小伙。");
        dic5.add("quality", "0");
        dic5.add("race", "5");
        dic5.add("career", "105");
        dic5.add("special_fetters", "0");
        dic5.add("range", "1");
        dic5.add("common_skill_id", "5");
        dic5.add("common_cd", "2");
        dic5.add("attack", "140.4");
        dic5.add("crit", "0.0229");
        dic5.add("burst", "1");
        dic5.add("special_skill_id", "1005");
        dic5.add("special_cd", "2");
        dic5.add("special_atk", "140.4");
        dic5.add("crit2", "0.0229");
        dic5.add("burst2", "1");
        dic5.add("gain_method", "0");
        this.infDic.add("5", dic5);
        let dic6 = new Dictionary<string, any>();
        dic6.add("id", "6");
        dic6.add("name", "石锤哥");
        dic6.add("story", "我不帅但我很厉害。");
        dic6.add("quality", "1");
        dic6.add("race", "1");
        dic6.add("career", "106");
        dic6.add("special_fetters", "0");
        dic6.add("range", "1");
        dic6.add("common_skill_id", "6");
        dic6.add("common_cd", "2");
        dic6.add("attack", "141.2");
        dic6.add("crit", "0.0242");
        dic6.add("burst", "1");
        dic6.add("special_skill_id", "1006");
        dic6.add("special_cd", "2");
        dic6.add("special_atk", "141.2");
        dic6.add("crit2", "0.0242");
        dic6.add("burst2", "1");
        dic6.add("gain_method", "0");
        this.infDic.add("6", dic6);
        let dic7 = new Dictionary<string, any>();
        dic7.add("id", "7");
        dic7.add("name", "投石力士");
        dic7.add("story", "谁说精灵都是很帅的？站出来，让我夸奖一下你。");
        dic7.add("quality", "1");
        dic7.add("race", "2");
        dic7.add("career", "107");
        dic7.add("special_fetters", "0");
        dic7.add("range", "1");
        dic7.add("common_skill_id", "7");
        dic7.add("common_cd", "2");
        dic7.add("attack", "141.8");
        dic7.add("crit", "0.0239");
        dic7.add("burst", "2");
        dic7.add("special_skill_id", "1007");
        dic7.add("special_cd", "2");
        dic7.add("special_atk", "141.8");
        dic7.add("crit2", "0.0239");
        dic7.add("burst2", "2");
        dic7.add("gain_method", "0");
        this.infDic.add("7", dic7);
        let dic8 = new Dictionary<string, any>();
        dic8.add("id", "8");
        dic8.add("name", "巨石大将");
        dic8.add("story", "他以脾气闻名，一言不合就开打。");
        dic8.add("quality", "1");
        dic8.add("race", "3");
        dic8.add("career", "101");
        dic8.add("special_fetters", "0");
        dic8.add("range", "1");
        dic8.add("common_skill_id", "8");
        dic8.add("common_cd", "1");
        dic8.add("attack", "141.6");
        dic8.add("crit", "0.0239");
        dic8.add("burst", "1");
        dic8.add("special_skill_id", "1008");
        dic8.add("special_cd", "1");
        dic8.add("special_atk", "141.6");
        dic8.add("crit2", "0.0239");
        dic8.add("burst2", "1");
        dic8.add("gain_method", "0");
        this.infDic.add("8", dic8);
        let dic9 = new Dictionary<string, any>();
        dic9.add("id", "9");
        dic9.add("name", "神奇小丑");
        dic9.add("story", "他的梦想是成为一个明星，但他只会扔火球。");
        dic9.add("quality", "1");
        dic9.add("race", "4");
        dic9.add("career", "102");
        dic9.add("special_fetters", "0");
        dic9.add("range", "1");
        dic9.add("common_skill_id", "9");
        dic9.add("common_cd", "4");
        dic9.add("attack", "141.4");
        dic9.add("crit", "0.0242");
        dic9.add("burst", "2");
        dic9.add("special_skill_id", "1009");
        dic9.add("special_cd", "4");
        dic9.add("special_atk", "141.4");
        dic9.add("crit2", "0.0242");
        dic9.add("burst2", "2");
        dic9.add("gain_method", "0");
        this.infDic.add("9", dic9);
        let dic10 = new Dictionary<string, any>();
        dic10.add("id", "10");
        dic10.add("name", "育火之灵");
        dic10.add("story", "来至异世界的智慧生物，小心别被他的火焰吞没。");
        dic10.add("quality", "3");
        dic10.add("race", "5");
        dic10.add("career", "103");
        dic10.add("special_fetters", "0");
        dic10.add("range", "1");
        dic10.add("common_skill_id", "10");
        dic10.add("common_cd", "4");
        dic10.add("attack", "145.8");
        dic10.add("crit", "0.0261");
        dic10.add("burst", "1");
        dic10.add("special_skill_id", "1010");
        dic10.add("special_cd", "4");
        dic10.add("special_atk", "145.8");
        dic10.add("crit2", "0.0261");
        dic10.add("burst2", "1");
        dic10.add("gain_method", "0");
        this.infDic.add("10", dic10);
        let dic11 = new Dictionary<string, any>();
        dic11.add("id", "11");
        dic11.add("name", "冰霜巨魔");
        dic11.add("story", "他擅长玩火，所以别让他靠近易燃易爆物品。");
        dic11.add("quality", "1");
        dic11.add("race", "1");
        dic11.add("career", "104");
        dic11.add("special_fetters", "0");
        dic11.add("range", "1");
        dic11.add("common_skill_id", "11");
        dic11.add("common_cd", "3");
        dic11.add("attack", "142.8");
        dic11.add("crit", "0.0243");
        dic11.add("burst", "2");
        dic11.add("special_skill_id", "1011");
        dic11.add("special_cd", "3");
        dic11.add("special_atk", "142.8");
        dic11.add("crit2", "0.0243");
        dic11.add("burst2", "2");
        dic11.add("gain_method", "0");
        this.infDic.add("11", dic11);
        let dic12 = new Dictionary<string, any>();
        dic12.add("id", "12");
        dic12.add("name", "火灵王");
        dic12.add("story", "可能因为兽潮的影响，他生来浑身通红，所以受到别人的排挤从此开始独自生活。");
        dic12.add("quality", "1");
        dic12.add("race", "2");
        dic12.add("career", "105");
        dic12.add("special_fetters", "0");
        dic12.add("range", "1");
        dic12.add("common_skill_id", "12");
        dic12.add("common_cd", "2");
        dic12.add("attack", "142");
        dic12.add("crit", "0.0245");
        dic12.add("burst", "1");
        dic12.add("special_skill_id", "1012");
        dic12.add("special_cd", "2");
        dic12.add("special_atk", "142");
        dic12.add("crit2", "0.0245");
        dic12.add("burst2", "1");
        dic12.add("gain_method", "0");
        this.infDic.add("12", dic12);
        let dic13 = new Dictionary<string, any>();
        dic13.add("id", "13");
        dic13.add("name", "魔莉");
        dic13.add("story", "她努力的学习！学习！学习！她找不到工作。");
        dic13.add("quality", "1");
        dic13.add("race", "3");
        dic13.add("career", "106");
        dic13.add("special_fetters", "0");
        dic13.add("range", "1");
        dic13.add("common_skill_id", "13");
        dic13.add("common_cd", "3");
        dic13.add("attack", "142.6");
        dic13.add("crit", "0.0241");
        dic13.add("burst", "1");
        dic13.add("special_skill_id", "1013");
        dic13.add("special_cd", "3");
        dic13.add("special_atk", "142.6");
        dic13.add("crit2", "0.0241");
        dic13.add("burst2", "1");
        dic13.add("gain_method", "0");
        this.infDic.add("13", dic13);
        let dic14 = new Dictionary<string, any>();
        dic14.add("id", "14");
        dic14.add("name", "俏皮花仙");
        dic14.add("story", "不要小看熊孩子的破坏力，她拥有破坏一切的技能。");
        dic14.add("quality", "2");
        dic14.add("race", "4");
        dic14.add("career", "107");
        dic14.add("special_fetters", "0");
        dic14.add("range", "1");
        dic14.add("common_skill_id", "14");
        dic14.add("common_cd", "3");
        dic14.add("attack", "143.2");
        dic14.add("crit", "0.0252");
        dic14.add("burst", "2");
        dic14.add("special_skill_id", "1014");
        dic14.add("special_cd", "3");
        dic14.add("special_atk", "143.2");
        dic14.add("crit2", "0.0252");
        dic14.add("burst2", "2");
        dic14.add("gain_method", "0");
        this.infDic.add("14", dic14);
        let dic15 = new Dictionary<string, any>();
        dic15.add("id", "15");
        dic15.add("name", "法术院长");
        dic15.add("story", "魔法学院的院长，据说她持有一把圣杖，能够驱逐兽潮带来的影响");
        dic15.add("quality", "2");
        dic15.add("race", "5");
        dic15.add("career", "101");
        dic15.add("special_fetters", "0");
        dic15.add("range", "1");
        dic15.add("common_skill_id", "15");
        dic15.add("common_cd", "3");
        dic15.add("attack", "144");
        dic15.add("crit", "0.0251");
        dic15.add("burst", "1");
        dic15.add("special_skill_id", "1015");
        dic15.add("special_cd", "3");
        dic15.add("special_atk", "144");
        dic15.add("crit2", "0.0251");
        dic15.add("burst2", "1");
        dic15.add("gain_method", "0");
        this.infDic.add("15", dic15);
        let dic16 = new Dictionary<string, any>();
        dic16.add("id", "16");
        dic16.add("name", "极法小玲");
        dic16.add("story", "流着东洋人血统，是个沉默寡言、表情稀少的少女，有以一敌百的战斗力");
        dic16.add("quality", "2");
        dic16.add("race", "1");
        dic16.add("career", "102");
        dic16.add("special_fetters", "0");
        dic16.add("range", "1");
        dic16.add("common_skill_id", "16");
        dic16.add("common_cd", "3");
        dic16.add("attack", "144.6");
        dic16.add("crit", "0.0249");
        dic16.add("burst", "2");
        dic16.add("special_skill_id", "1016");
        dic16.add("special_cd", "3");
        dic16.add("special_atk", "144.6");
        dic16.add("crit2", "0.0249");
        dic16.add("burst2", "2");
        dic16.add("gain_method", "0");
        this.infDic.add("16", dic16);
        let dic17 = new Dictionary<string, any>();
        dic17.add("id", "17");
        dic17.add("name", "长矛战神");
        dic17.add("story", "使用长矛作为武器的格斗家，能够引导闪电的力量。");
        dic17.add("quality", "3");
        dic17.add("race", "2");
        dic17.add("career", "103");
        dic17.add("special_fetters", "0");
        dic17.add("range", "1");
        dic17.add("common_skill_id", "17");
        dic17.add("common_cd", "3");
        dic17.add("attack", "145.2");
        dic17.add("crit", "0.0262");
        dic17.add("burst", "1");
        dic17.add("special_skill_id", "1017");
        dic17.add("special_cd", "3");
        dic17.add("special_atk", "145.2");
        dic17.add("crit2", "0.0262");
        dic17.add("burst2", "1");
        dic17.add("gain_method", "0");
        this.infDic.add("17", dic17);
        let dic18 = new Dictionary<string, any>();
        dic18.add("id", "18");
        dic18.add("name", "轻鸿长枪");
        dic18.add("story", "上古神秘科技的产物，拥有一把长矛却轻如鸿毛。");
        dic18.add("quality", "3");
        dic18.add("race", "3");
        dic18.add("career", "104");
        dic18.add("special_fetters", "0");
        dic18.add("range", "1");
        dic18.add("common_skill_id", "18");
        dic18.add("common_cd", "2");
        dic18.add("attack", "145.8");
        dic18.add("crit", "0.0261");
        dic18.add("burst", "2");
        dic18.add("special_skill_id", "1018");
        dic18.add("special_cd", "2");
        dic18.add("special_atk", "145.8");
        dic18.add("crit2", "0.0261");
        dic18.add("burst2", "2");
        dic18.add("gain_method", "0");
        this.infDic.add("18", dic18);
        let dic19 = new Dictionary<string, any>();
        dic19.add("id", "19");
        dic19.add("name", "舞之空");
        dic19.add("story", "地表最强外星人！");
        dic19.add("quality", "4");
        dic19.add("race", "4");
        dic19.add("career", "105");
        dic19.add("special_fetters", "0");
        dic19.add("range", "1");
        dic19.add("common_skill_id", "19");
        dic19.add("common_cd", "4");
        dic19.add("attack", "147.6");
        dic19.add("crit", "0.0269");
        dic19.add("burst", "1");
        dic19.add("special_skill_id", "1019");
        dic19.add("special_cd", "4");
        dic19.add("special_atk", "147.6");
        dic19.add("crit2", "0.0269");
        dic19.add("burst2", "1");
        dic19.add("gain_method", "0");
        this.infDic.add("19", dic19);
        let dic20 = new Dictionary<string, any>();
        dic20.add("id", "20");
        dic20.add("name", "纯铁之拳");
        dic20.add("story", "随身携带月光宝盒，让敌人回到4秒之前的位置，并在时间旋涡里无尽轮回。");
        dic20.add("quality", "4");
        dic20.add("race", "5");
        dic20.add("career", "106");
        dic20.add("special_fetters", "0");
        dic20.add("range", "1");
        dic20.add("common_skill_id", "20");
        dic20.add("common_cd", "3");
        dic20.add("attack", "148");
        dic20.add("crit", "0.0272");
        dic20.add("burst", "1");
        dic20.add("special_skill_id", "1020");
        dic20.add("special_cd", "3");
        dic20.add("special_atk", "148");
        dic20.add("crit2", "0.0272");
        dic20.add("burst2", "1");
        dic20.add("gain_method", "0");
        this.infDic.add("20", dic20);
        let dic21 = new Dictionary<string, any>();
        dic21.add("id", "21");
        dic21.add("name", "洋明王");
        dic21.add("story", "使用三叉戟作为武器的格斗家。");
        dic21.add("quality", "3");
        dic21.add("race", "1");
        dic21.add("career", "107");
        dic21.add("special_fetters", "0");
        dic21.add("range", "1");
        dic21.add("common_skill_id", "21");
        dic21.add("common_cd", "1");
        dic21.add("attack", "145.8");
        dic21.add("crit", "0.0261");
        dic21.add("burst", "2");
        dic21.add("special_skill_id", "1021");
        dic21.add("special_cd", "1");
        dic21.add("special_atk", "145.8");
        dic21.add("crit2", "0.0261");
        dic21.add("burst2", "2");
        dic21.add("gain_method", "0");
        this.infDic.add("21", dic21);
        let dic22 = new Dictionary<string, any>();
        dic22.add("id", "22");
        dic22.add("name", "古牛王者");
        dic22.add("story", "拥有拔山裂地的能力，力大无穷。");
        dic22.add("quality", "3");
        dic22.add("race", "2");
        dic22.add("career", "101");
        dic22.add("special_fetters", "0");
        dic22.add("range", "1");
        dic22.add("common_skill_id", "22");
        dic22.add("common_cd", "2");
        dic22.add("attack", "145.6");
        dic22.add("crit", "0.0263");
        dic22.add("burst", "1");
        dic22.add("special_skill_id", "1022");
        dic22.add("special_cd", "2");
        dic22.add("special_atk", "145.6");
        dic22.add("crit2", "0.0263");
        dic22.add("burst2", "1");
        dic22.add("gain_method", "0");
        this.infDic.add("22", dic22);
        let dic23 = new Dictionary<string, any>();
        dic23.add("id", "23");
        dic23.add("name", "魔性蛮牛");
        dic23.add("story", "因为红孩儿离家出走而魔化，最听不得的字是“猴”。");
        dic23.add("quality", "3");
        dic23.add("race", "3");
        dic23.add("career", "102");
        dic23.add("special_fetters", "0");
        dic23.add("range", "1");
        dic23.add("common_skill_id", "23");
        dic23.add("common_cd", "1");
        dic23.add("attack", "146.8");
        dic23.add("crit", "0.0267");
        dic23.add("burst", "2");
        dic23.add("special_skill_id", "1023");
        dic23.add("special_cd", "1");
        dic23.add("special_atk", "146.8");
        dic23.add("crit2", "0.0267");
        dic23.add("burst2", "2");
        dic23.add("gain_method", "0");
        this.infDic.add("23", dic23);
        let dic24 = new Dictionary<string, any>();
        dic24.add("id", "24");
        dic24.add("name", "大力摔手");
        dic24.add("story", "普普通通的摔跤手，喜欢赌钱和喝酒。");
        dic24.add("quality", "1");
        dic24.add("race", "4");
        dic24.add("career", "103");
        dic24.add("special_fetters", "0");
        dic24.add("range", "1");
        dic24.add("common_skill_id", "24");
        dic24.add("common_cd", "3");
        dic24.add("attack", "141.6");
        dic24.add("crit", "0.0242");
        dic24.add("burst", "1");
        dic24.add("special_skill_id", "1024");
        dic24.add("special_cd", "3");
        dic24.add("special_atk", "141.6");
        dic24.add("crit2", "0.0242");
        dic24.add("burst2", "1");
        dic24.add("gain_method", "0");
        this.infDic.add("24", dic24);
        let dic25 = new Dictionary<string, any>();
        dic25.add("id", "25");
        dic25.add("name", "神坎特");
        dic25.add("story", "力大无比的角斗士，一餐能吃掉一头牛。");
        dic25.add("quality", "2");
        dic25.add("race", "5");
        dic25.add("career", "104");
        dic25.add("special_fetters", "0");
        dic25.add("range", "1");
        dic25.add("common_skill_id", "25");
        dic25.add("common_cd", "2");
        dic25.add("attack", "143.8");
        dic25.add("crit", "0.0251");
        dic25.add("burst", "2");
        dic25.add("special_skill_id", "1025");
        dic25.add("special_cd", "2");
        dic25.add("special_atk", "143.8");
        dic25.add("crit2", "0.0251");
        dic25.add("burst2", "2");
        dic25.add("gain_method", "0");
        this.infDic.add("25", dic25);
        let dic26 = new Dictionary<string, any>();
        dic26.add("id", "26");
        dic26.add("name", "维京蛮人");
        dic26.add("story", "城市中最普通不过的护卫，对于那些穷凶极恶之徒，他们通常的处理方式是：假装没看见。");
        dic26.add("quality", "1");
        dic26.add("race", "1");
        dic26.add("career", "105");
        dic26.add("special_fetters", "0");
        dic26.add("range", "1");
        dic26.add("common_skill_id", "26");
        dic26.add("common_cd", "3");
        dic26.add("attack", "142.4");
        dic26.add("crit", "0.0243");
        dic26.add("burst", "1");
        dic26.add("special_skill_id", "1026");
        dic26.add("special_cd", "3");
        dic26.add("special_atk", "142.4");
        dic26.add("crit2", "0.0243");
        dic26.add("burst2", "1");
        dic26.add("gain_method", "0");
        this.infDic.add("26", dic26);
        let dic27 = new Dictionary<string, any>();
        dic27.add("id", "27");
        dic27.add("name", "维京巨刃");
        dic27.add("story", "燃烧的剑，燃烧的心。");
        dic27.add("quality", "2");
        dic27.add("race", "2");
        dic27.add("career", "106");
        dic27.add("special_fetters", "0");
        dic27.add("range", "1");
        dic27.add("common_skill_id", "27");
        dic27.add("common_cd", "3");
        dic27.add("attack", "144.2");
        dic27.add("crit", "0.025");
        dic27.add("burst", "1");
        dic27.add("special_skill_id", "1027");
        dic27.add("special_cd", "3");
        dic27.add("special_atk", "144.2");
        dic27.add("crit2", "0.025");
        dic27.add("burst2", "1");
        dic27.add("gain_method", "0");
        this.infDic.add("27", dic27);
        let dic28 = new Dictionary<string, any>();
        dic28.add("id", "28");
        dic28.add("name", "中古之锤");
        dic28.add("story", "残血秒杀：血量低于15%的敌人，一击毙命！");
        dic28.add("quality", "4");
        dic28.add("race", "3");
        dic28.add("career", "107");
        dic28.add("special_fetters", "0");
        dic28.add("range", "1");
        dic28.add("common_skill_id", "28");
        dic28.add("common_cd", "4");
        dic28.add("attack", "147.2");
        dic28.add("crit", "0.0272");
        dic28.add("burst", "2");
        dic28.add("special_skill_id", "1028");
        dic28.add("special_cd", "4");
        dic28.add("special_atk", "147.2");
        dic28.add("crit2", "0.0272");
        dic28.add("burst2", "2");
        dic28.add("gain_method", "0");
        this.infDic.add("28", dic28);
        let dic29 = new Dictionary<string, any>();
        dic29.add("id", "29");
        dic29.add("name", "智慧树人");
        dic29.add("story", "最有智慧的生命（毕竟谁也没他活的时间长），洞悉一切敌人的弱点！");
        dic29.add("quality", "4");
        dic29.add("race", "4");
        dic29.add("career", "101");
        dic29.add("special_fetters", "0");
        dic29.add("range", "1");
        dic29.add("common_skill_id", "29");
        dic29.add("common_cd", "3");
        dic29.add("attack", "147.8");
        dic29.add("crit", "0.0271");
        dic29.add("burst", "1");
        dic29.add("special_skill_id", "1029");
        dic29.add("special_cd", "3");
        dic29.add("special_atk", "147.8");
        dic29.add("crit2", "0.0271");
        dic29.add("burst2", "1");
        dic29.add("gain_method", "0");
        this.infDic.add("29", dic29);
        let dic30 = new Dictionary<string, any>();
        dic30.add("id", "30");
        dic30.add("name", "力之雕像");
        dic30.add("story", "兽人守护者的雕像");
        dic30.add("quality", "2");
        dic30.add("race", "5");
        dic30.add("career", "102");
        dic30.add("special_fetters", "0");
        dic30.add("range", "1");
        dic30.add("common_skill_id", "30");
        dic30.add("common_cd", "0");
        dic30.add("attack", "0");
        dic30.add("crit", "0");
        dic30.add("burst", "2");
        dic30.add("special_skill_id", "1030");
        dic30.add("special_cd", "0");
        dic30.add("special_atk", "0");
        dic30.add("crit2", "0");
        dic30.add("burst2", "2");
        dic30.add("gain_method", "0");
        this.infDic.add("30", dic30);
        let dic31 = new Dictionary<string, any>();
        dic31.add("id", "31");
        dic31.add("name", "惰之雕像");
        dic31.add("story", "走过路过全部变慢");
        dic31.add("quality", "2");
        dic31.add("race", "1");
        dic31.add("career", "103");
        dic31.add("special_fetters", "0");
        dic31.add("range", "1");
        dic31.add("common_skill_id", "31");
        dic31.add("common_cd", "0");
        dic31.add("attack", "0");
        dic31.add("crit", "0");
        dic31.add("burst", "1");
        dic31.add("special_skill_id", "1031");
        dic31.add("special_cd", "0");
        dic31.add("special_atk", "0");
        dic31.add("crit2", "0");
        dic31.add("burst2", "1");
        dic31.add("gain_method", "0");
        this.infDic.add("31", dic31);
        let dic32 = new Dictionary<string, any>();
        dic32.add("id", "32");
        dic32.add("name", "速之雕像");
        dic32.add("story", "精灵守护者的雕像");
        dic32.add("quality", "2");
        dic32.add("race", "2");
        dic32.add("career", "104");
        dic32.add("special_fetters", "0");
        dic32.add("range", "1");
        dic32.add("common_skill_id", "32");
        dic32.add("common_cd", "0");
        dic32.add("attack", "0");
        dic32.add("crit", "0");
        dic32.add("burst", "2");
        dic32.add("special_skill_id", "1032");
        dic32.add("special_cd", "0");
        dic32.add("special_atk", "0");
        dic32.add("crit2", "0");
        dic32.add("burst2", "2");
        dic32.add("gain_method", "0");
        this.infDic.add("32", dic32);
        let dic33 = new Dictionary<string, any>();
        dic33.add("id", "33");
        dic33.add("name", "黑魔导女孩");
        dic33.add("story", "低调的华丽，藏不住的破坏力！");
        dic33.add("quality", "3");
        dic33.add("race", "3");
        dic33.add("career", "105");
        dic33.add("special_fetters", "0");
        dic33.add("range", "1");
        dic33.add("common_skill_id", "33");
        dic33.add("common_cd", "3");
        dic33.add("attack", "146.6");
        dic33.add("crit", "0.0261");
        dic33.add("burst", "1");
        dic33.add("special_skill_id", "1033");
        dic33.add("special_cd", "3");
        dic33.add("special_atk", "146.6");
        dic33.add("crit2", "0.0261");
        dic33.add("burst2", "1");
        dic33.add("gain_method", "0");
        this.infDic.add("33", dic33);
        let dic34 = new Dictionary<string, any>();
        dic34.add("id", "34");
        dic34.add("name", "小冰冰");
        dic34.add("story", "不会攻击，但是会给敌人减速，给队友加速，全场最佳不含糊！");
        dic34.add("quality", "4");
        dic34.add("race", "4");
        dic34.add("career", "106");
        dic34.add("special_fetters", "0");
        dic34.add("range", "1");
        dic34.add("common_skill_id", "34");
        dic34.add("common_cd", "1");
        dic34.add("attack", "0");
        dic34.add("crit", "0");
        dic34.add("burst", "1");
        dic34.add("special_skill_id", "1034");
        dic34.add("special_cd", "1");
        dic34.add("special_atk", "0");
        dic34.add("crit2", "0");
        dic34.add("burst2", "1");
        dic34.add("gain_method", "0");
        this.infDic.add("34", dic34);
        let dic35 = new Dictionary<string, any>();
        dic35.add("id", "35");
        dic35.add("name", "崩坏少女");
        dic35.add("story", "谁走的慢就打死谁！");
        dic35.add("quality", "4");
        dic35.add("race", "5");
        dic35.add("career", "107");
        dic35.add("special_fetters", "0");
        dic35.add("range", "1");
        dic35.add("common_skill_id", "35");
        dic35.add("common_cd", "3");
        dic35.add("attack", "147.6");
        dic35.add("crit", "0.0273");
        dic35.add("burst", "2");
        dic35.add("special_skill_id", "1035");
        dic35.add("special_cd", "3");
        dic35.add("special_atk", "147.6");
        dic35.add("crit2", "0.0273");
        dic35.add("burst2", "2");
        dic35.add("gain_method", "0");
        this.infDic.add("35", dic35);
        let dic36 = new Dictionary<string, any>();
        dic36.add("id", "36");
        dic36.add("name", "念狮之王");
        dic36.add("story", "狮王查姆，玛莎王朝的守护人，改革春风...");
        dic36.add("quality", "4");
        dic36.add("race", "1");
        dic36.add("career", "101");
        dic36.add("special_fetters", "0");
        dic36.add("range", "1");
        dic36.add("common_skill_id", "36");
        dic36.add("common_cd", "3");
        dic36.add("attack", "147.8");
        dic36.add("crit", "0.0271");
        dic36.add("burst", "1");
        dic36.add("special_skill_id", "1036");
        dic36.add("special_cd", "3");
        dic36.add("special_atk", "147.8");
        dic36.add("crit2", "0.0271");
        dic36.add("burst2", "1");
        dic36.add("gain_method", "0");
        this.infDic.add("36", dic36);
    }
    
}
